#pragma once

#define PLUGIN_VERSION				0x01000000
#define PLUGIN_VERSION_STRING		"1.0.0"
#define PLUGIN_NAME_SHORT			"BetterCriticals"
#define PLUGIN_NAME					"Better Criticals"
#define SUPPORTED_RUNTIME_VERSION   CURRENT_RELEASE_RUNTIME
#define MINIMUM_RUNTIME_VERSION     CURRENT_RELEASE_RUNTIME